### ISSUE TITLE
Chrome Eklentisi Kurulmuyor

### ISSUE THREAD

**Issue by ghost** [sh4dowb/eba-canli-ders-crossplatform#10]
Merhaba. Chrome için olan eklentiyi indirip kurmaya çalıştığım zaman resimdeki hatayı alıyorum. Chrome 87.0.4280.88 (Resmi Derleme) (64 bit) Sürümü. 
![Ekran görüntüsü 2020-12-16 14-50-03](https://user-images.githubusercontent.com/41836521/102345211-0ecb5c80-3fae-11eb-99f1-f01cb213b786.png)

**Comment by sh4dowb** [comment]
selam, tekrar denemeniz mümkün mü eklenti dosyası chrome yeni sürüme uyacak şekilde güncellendi

**Comment by ghost** [comment]
Aynı hata hâlâ geçerli.

**Comment by sh4dowb** [comment]
> Aynı hata hâlâ geçerli.

gizli moddan tekrar indirir misiniz, önbellekte olabilir

**Comment by ghost** [comment]
Curl ile indirip kurdum bu sefer oldu, teşekkürler.
