### ISSUE TITLE
Firefox eklentisi Invalid ID

### ISSUE THREAD

**Issue by jn-sena** [sh4dowb/eba-canli-ders-crossplatform#3]
Eba Lacivert sayfadayken **Firefox** eklentesini kullanarak, **öğrenci** olarak girince `zoom` sayfasına atıyor ve `Invalid ID` hatası veriyor.

Örnek Fotoğraf:
![image](https://user-images.githubusercontent.com/45771313/94336120-3af7c280-ffe9-11ea-90a8-415285b63df4.png)

Örnek Link:
`https://us02web.zoom.us/w/89079591789?tk=hVoW0YmQxAnVgQDEF2B8mRRQUuj2_hG2GmRai1JtZ-A.DQIAAAAUvY6zbRZHeVpxbWNhYlRKV09YMGpMb19vbDdRAAAAAAAAAAAAAAAAAAAAAAAAAAAA%26pwd%3DTUFmN0ozTlFaSTJHVjRRNE5iMERDZz09`

Eba Sürümü: VCollabPlayer_v0.0.714

**Comment by jn-sena** [comment]
Belirtmeyi unuttum;

```javascript
$.getScript("https://cagriari.com/eba-ogrenci.js");
```

şeklinde kullanınca çalışıyor.

**Comment by sh4dowb** [comment]
merhaba, eklentinin son versiyonunda bu sorun çözüldü, eski versiyonu kaldırıp, https://cagriari.com/eba.xpi adresinden tekrar kurmayı dener misiniz?

**Comment by jn-sena** [comment]
Evet çalışıyor. Kusura bakmayın.
