### ISSUE TITLE
403 -"uygulama-ebaders..."

### ISSUE THREAD

**Issue by ghost** [sh4dowb/eba-canli-ders-crossplatform#4]
https://user-images.githubusercontent.com/68079258/94936803-6d1c8f00-04d7-11eb-84a3-645cd05af964.png

Öğrencide sorun yok.

**Comment by bytescreator** [comment]
Ekranda bu aralıkta ne vardı? Öğretmenlerin EBA'sı değişmiş olabilir.

**Comment by ghost** [comment]
Dün çalışıyordu bugün çalışmıyor.

**Comment by bytescreator** [comment]
Hatayı hangi sayfada alıyorsunuz?

**Comment by ghost** [comment]
"Dersin başlamasına ... dk kaldı" Sayfasında.

**Comment by sh4dowb** [comment]
eba'daki JS dosyasında URL güncellenmiştir muhtemelen, bugün ilgileneceğim

**Comment by bytescreator** [comment]
Öğrenci misiniz yoksa öğretmen mi?

**Comment by ghost** [comment]
Öğrenci

**Comment by bytescreator** [comment]
Öğrencide çalışmaması normal, öğretmen adresi. EBA'nın asıl sayfasında çalışmıştır ancak böyle hata almamışsınızdır. Öğrenciyi kullanın. Öğretmeni değil.

**Comment by ghost** [comment]
Dün çalışıyordu ama neyse, teşekkürler.
