### ISSUE TITLE
Invalid meeting ID hatası

### ISSUE THREAD

**Issue by umtcnyd** [sh4dowb/eba-canli-ders-crossplatform#6]
Eklentiyi (crx) yada betiği kullanınca Zoom'un sitesi açılıyor lakin sadece meeting ID'nin hatalı olduğunu gösteren bir mesaj veriyor. Onun dışında açılan sekmenin URL'sinden ID'yi kopyalayıp normal Zoom'dan girince ID çalışıyor, önceden böyle bir şey olmuyordu.

![image](https://user-images.githubusercontent.com/74899342/99942914-7a405680-2d81-11eb-9c65-c28045f9d188.png)

**Comment by sh4dowb** [comment]
öğrencide mavi ekrandaki hata son commit ile çözülmüş olması lazım
düzenleme: bazı öğrenciler için hala çalışmıyor sanırım, çözmeye çalışıyorum

**Comment by umtcnyd** [comment]
> öğrencide mavi ekrandaki hata son commit ile çözülmüş olması lazım

Maalesef devam ediyor aynı hata.

**Comment by tx8r** [comment]
Bende aynı hatayı alıyorum maalesef :(

**Comment by tx8r** [comment]
Aynı hatayı ben de alıyorum

**Comment by umtcnyd** [comment]
Düzelttiniz mi bilmiyorum ama son commit hala sorunu çözmedi.

**Comment by ysfsvm** [comment]
> Düzelttiniz mi bilmiyorum ama son commit hala sorunu çözmedi.

Sorun hala birebir aynı mı?
ve son commit ile bir değişiklik oldu mu?

**Comment by umtcnyd** [comment]
> > Düzelttiniz mi bilmiyorum ama son commit hala sorunu çözmedi.
> 
> Sorun hala birebir aynı mı?
> ve son commit ile bir değişiklik oldu mu?

Bugün canlı dersim olmadığı için maalesef deneyemem. Yarın tekrar kontrol edip yazarım.

**Comment by sh4dowb** [comment]
#5
