### ISSUE TITLE
Firefox Eklentisi Çalışmıyor

### ISSUE THREAD

**Issue by TalkingPanda0** [sh4dowb/eba-canli-ders-crossplatform#8]
Firefoxda eklentiden ok basınca ekrana hiç bişey gelmiyor scripte çalıştırınca çalışıyor chromiumda çalışıyor 
![2020-12-08 17-14-24](https://user-images.githubusercontent.com/69118613/101499435-2f1f6980-3965-11eb-9d4a-4ee419a42102.gif)

**Comment by sh4dowb** [comment]
az önce denedim ve çalıştı, rica etsem F12 basıp console kısmında hata var mı, bakabilir misiniz?

**Comment by TalkingPanda0** [comment]
![2020-12-09_14-31](https://user-images.githubusercontent.com/69118613/101624761-554f1300-3a12-11eb-8e13-2ae0e165e86d.png)

**Comment by bytescreator** [comment]
@sh4dowb Ajax'lara error fonksiyonu eklemek hatayı belli edebilir. Muhtemelen 1. ya da 2. istekte bir hata oluşuyor, ondan ötürü çalışmıyor. 

@TalkingPanda0 Network kısmına bakabilirmisiniz 
- https://ders.eba.gov.tr/ders/getlivelessoninfo
- https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService/livelesson/inpage/instudytime/join 
- https://cagriari.com/eba_nonceproxy.php en son da bu adrese istek yapılıyor, bunlardan birinde sıkıntı var ondan çalışmıyor.

*.eba.gov.tr olan adreslerin HTTP durum kodlarına ve ebanın eklediği yanıttaki `success` parametresine bakın. 500 durum kodu yok NetworkError verirdi o durumda. muhtemelen bir yerde 403 geliyor.

**Comment by TalkingPanda0** [comment]
@bytescreator Firefox eklentisini kullanınca network kısmına hiç birşey gelmiyor Chromium veya scripte bunlar geliyor
![chromium](https://user-images.githubusercontent.com/69118613/101780182-1d1d0280-3aee-11eb-993b-4f92781c628a.png)

**Comment by bytescreator** [comment]
@TalkingPanda0 Doğru, firefox eklenti trafiğini göstermiyor unutmuşum (@sh4dowb nin error fonksiyonlarını eklemesi lazim). Ancak chrome'da son istekte takılmış gibi duruyor doğru mudur?(Chrome'da çalışıyordu gerçi)

Firefox'da network.trr.mode ayarını değistirdiniz mi hiç? Bende bir kere cagriari.com 'a erişememiştim bundan dolayıymış

**Comment by TalkingPanda0** [comment]
ekran görüntüsünü zoom'u açmadan aldığım için öyle gözüküyor. Firefox'da network.trr.mode 2 ye ayarlamışım sıfırladım yine çalışmıyor.

**Comment by sh4dowb** [comment]
firefoxta network kısmında bir şey çıkmıyorsa `about:debugging#/runtime/this-firefox` dan inspect yapıp ordan görebilirsiniz

**Comment by TalkingPanda0** [comment]
about:debugging#/runtime/this-firefox dan inspecte bastım networke bastım eklentiye kullandım networke birşey gelmedi
![2020-12-12_16-37](https://user-images.githubusercontent.com/69118613/101985315-2e494900-3c7f-11eb-950f-bb275cc2d759.png)

**Comment by bytescreator** [comment]
@sh4dowb Benim derste denedim bende de çalışmadı :D

sebebi CORS, manifest'te https://cagriari.com/eba_nonceproxy.php 'i eklemek
```
  "permissions":["tabs", "activeTab", "*://*.eba.gov.tr/*","https://cagriari.com/eba_nonceproxy.php"],
```
 ya da
```
url: "https://uygulama-ebaders.eba.gov.tr/FrontEndService/livelesson/nonce/"+encodeURIComponent(resp2.meeting.token),
```
bunu kullanmak lazım bunları değiştirince çalıştı bende
acaba daha önce neden çalışıyordu. Firefox güvenlik yamasından olabilir, geçenlerde önemli birkaç açık kapatıldı, onların arasında bunu da değiştirmiş olabilirler.

**Comment by sh4dowb** [comment]
> @sh4dowb Benim derste denedim bende de çalışmadı :D
> 
> sebebi CORS, manifest'te https://cagriari.com/eba_nonceproxy.php 'i eklemek
> 
> ```
>   "permissions":["tabs", "activeTab", "*://*.eba.gov.tr/*","https://cagriari.com/eba_nonceproxy.php"],
> ```
> 
> ya da
> 
> ```
> url: "https://uygulama-ebaders.eba.gov.tr/FrontEndService/livelesson/nonce/"+encodeURIComponent(resp2.meeting.token),
> ```
> 
> bunu kullanmak lazım bunları değiştirince çalıştı bende
> acaba daha önce neden çalışıyordu. Firefox güvenlik yamasından olabilir, geçenlerde önemli birkaç açık kapatıldı, onların arasında bunu da değiştirmiş olabilirler.

doğru, onu gözden kaçırmışım
imkanınız varsa pr atıp xpi ve crx (zip) dosyasını iletmeniz mümkün mü acaba, şuan taşındığım için bilgisayara erişimim yok maalesef
teşekkürler

**Comment by bytescreator** [comment]
xpi olarak denemedim de debug modda geçici yükleme yaparak çalıştırdım, xpi mozilla imzalı sanırım onun yerine tarayici_eklenti klasörünü değiştirmek yeterli olur mu

**Comment by sh4dowb** [comment]
> xpi olarak denemedim de debug modda geçici yükleme yaparak çalıştırdım, xpi mozilla imzalı sanırım onun yerine tarayici_eklenti klasörünü değiştirmek yeterli olur mu

evet hocam yeterli olacaktır çok sağolun
